### ISSUE TITLE
Add character error

### ISSUE THREAD

**Issue by cyanst** [pyfa-org/pyfa.io#2]
Pyfa v 2.43.0, error while trying to import character token
![image](https://user-images.githubusercontent.com/88346254/169659958-acff26bc-9e1a-46a3-9e67-0454965a3d84.png)
Character: Aquamarine Cyanide Die
Account: Aquamarice CSG
Pyfa SSO settings: 
![image](https://user-images.githubusercontent.com/88346254/169660007-dc564765-de6c-422d-8ebb-7cf3521815a7.png)
Character token: eyJjb2RlIjoiam4zTGpFQVRXa2E0VExURzczRVBmZyIsInN0YXRlIjoiZXlKdGIyUmxJam9nTVN3Z0luSmxaR2x5WldOMElqb2diblZzYkN3Z0luTjBZWFJsSWpvZ0lqYzRPVEpoTldNMUxXUmxNRGN0TkRSaU55MWhNVEk1TFRSbE5EVmhZVE0yTXpZeE1DSjkifQ==
How encountered: entered token in SSO character management->add character.

**Comment by cyanst** [comment]
Tried with character editor:
pyfa v2.43.0
EVE Data Version: 2040917 (2022-05-05 13:28:05)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.27.1
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "service\esiAccess.py", line 244, in validate_eve_jwt
  File "site-packages\jose\jwt.py", line 153, in decode
  File "site-packages\jose\jwt.py", line 461, in _validate_claims
  File "site-packages\jose\jwt.py", line 302, in _validate_exp
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\characterEditor.py", line 826, in addCharacter
  File "service\esi.py", line 112, in login
  File "service\esi.py", line 138, in handleLogin
  File "service\esiAccess.py", line 178, in auth
  File "service\esiAccess.py", line 247, in validate_eve_jwt
service.esiAccess.GenericSsoError: The JWT token has expired: Signature has expired.
